### ISSUE TITLE
Update to version 1.3.0

### ISSUE THREAD

**Issue by davisonio** [fantattitude/refined-github-safari#3]
Version 1.3.0 has just been released, could you update the Safari version? https://github.com/sindresorhus/refined-github/commit/6637386ac71c03ed35f39f5925b16903cdafa2f2

**Comment by fantattitude** [comment]
As stated in #1 I can't get it to work because of some strange behavior when converting the scripts to ES5 with Babel. I didn't find any info on how to fix it currently.

**Comment by schrodincat** [comment]
Is there any progress towards the new up-to-date release?

**Comment by fantattitude** [comment]
The lack of some APIs in Safari and the evolution of the original extension made me stop working on updates but if you have knowledge on it you can contribute 😉
